var nickname = {
    ending: {
        male: 'ый',
        male2: 'ой',
        male3: 'ий',
        female: 'ая',
    },
    nouns: [
        { label: 'Куропатка', gender: 'female' },
        { label: 'Кенгуру', gender: 'male' },
        { label: 'Заяц', gender: 'male' },
        { label: 'Гипопотам', gender: 'male' },
        { label: 'Волк', gender: 'male' },
        { label: 'Собака', gender: 'female' },
        { label: 'Слон', gender: 'male' },
        { label: 'Зайчиха', gender: 'female' },
        { label: 'Мышь', gender: 'female' },
        { label: 'Тушканчик', gender: 'male' },
        { label: 'Свинка', gender: 'female' },
        { label: 'Кит', gender: 'male' },
        { label: 'Акула', gender: 'female' },
        { label: 'Кошка', gender: 'female' },
        { label: 'Удав', gender: 'male' },
        { label: 'Когтекрыл', gender: 'male' },
        { label: 'Червь', gender: 'male' },
        { label: 'Курица', gender: 'female' },
        { label: 'Орел', gender: 'male' },
        { label: 'Слизень', gender: 'male' },
        { label: 'Лев', gender: 'male' },
        { label: 'Пантера', gender: 'female' },
        { label: 'Гиена', gender: 'female' },
        { label: 'Кобра', gender: 'female' },
        { label: 'Муха', gender: 'female' },
        { label: 'Панда', gender: 'female' },
        { label: 'Медведь', gender: 'male' },
        { label: 'Гусь', gender: 'male' },
        { label: 'Утка', gender: 'female' },
        { label: 'Обезьяна', gender: 'female' },
        { label: 'Попугай', gender: 'male' },
    ],
    rand: function (min, max) {
      return Math.random() * (max - min) + min
    },
    generate: function () {
        let adjective = nickname.adjectives[Math.floor(nickname.rand(0, nickname.adjectives.length-1))]
        let noun = nickname.nouns[Math.floor(nickname.rand(0, nickname.nouns.length-1))]
        let name = adjective.label + (noun.gender === 'male' ? adjective.alt ? adjective.alt : nickname.ending.male : nickname.ending.female)
        return name + ' ' + noun.label
    }
}
nickname.adjectives = [
    {label: 'Латентн'},
    {label: 'Весел'},
    {label: 'Интригующ', alt: nickname.ending.male3},
    {label: 'Красн'},
    {label: 'Застенчив'},
    {label: 'Крохотн'},
    {label: 'Большевит'},
    {label: 'Зелен'},
    {label: 'Пурпурн'},
    {label: 'Мелк', alt: nickname.ending.male3},
    {label: 'Зл', alt: nickname.ending.male2},
    {label: 'Толст'},
    {label: 'Худ', alt: nickname.ending.male2},
    {label: 'Млечющ', alt: nickname.ending.male3},
    {label: 'Бледн'},
    {label: 'Охотлив'},
    {label: 'Бугурт'},
    {label: 'Черн'},
    {label: 'Укурен'},
    {label: 'Грустн'},
    {label: 'Бел'},
    {label: 'Морск', alt: nickname.ending.male2},
    {label: 'Оранжев'},
    {label: 'Прост', alt: nickname.ending.male2},
    {label: 'Больш', alt: nickname.ending.male2},
    {label: 'Тускл'},
    {label: 'Бел'},
    {label: 'Ветрян', alt: nickname.ending.male2},
    {label: 'Дрян', alt: nickname.ending.male2},
    {label: 'Азиатск', alt: nickname.ending.male3},
    {label: 'Магическ', alt: nickname.ending.male3},
    {label: 'Жадн'},
    {label: 'Волосат'},
    {label: 'Космическ', alt: nickname.ending.male3},
    {label: 'Пьян'},
]

module.exports = nickname
